DROP TABLE IF EXISTS lists CASCADE;

CREATE TABLE lists (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES user(id) ON DELETE CASCADE,
  widget_id INTEGER REFERENCES widget(id) ON DELETE CASCADE,
  name VARCHAR(255),
  description TEXT
);